// <auto-generated />
using System;
using AzilEdu.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Azil.Api.Migrations
{
    [DbContext(typeof(AzilEduDbContext))]
    [Migration("20260723170208_AddVolunteerTasks")]
    partial class AddVolunteerTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AzilEdu.Shared.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalStatusId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AnimalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnimalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dostupna za udomljenje"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rezervirana"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Udomljena"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Na liječenju"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonorStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonorTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DonorStatusId");

                    b.HasIndex("DonorTypeId");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonorStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DonorStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Novi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aktivan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Povremeni"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Neaktivan"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DonorTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fizička osoba"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tvrtka"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Udruga ili organizacija"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeePositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePositionId");

                    b.HasIndex("EmployeeStatusId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.EmployeePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmployeePositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Djelatnik azila"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Veterinar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Koordinator volontera"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.EmployeeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmployeeStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aktivan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Na dopustu ili bolovanju"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Neaktivan"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.HousingUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCleanedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Occupied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HousingUnits");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AvailableFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VolunteerStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VolunteerStatusId");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VolunteerStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Novi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aktivan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Privremeno nedostupan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Neaktivan"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerTaskStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerTaskTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("VolunteerTaskStatusId");

                    b.HasIndex("VolunteerTaskTypeId");

                    b.ToTable("VolunteerTasks");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTaskStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VolunteerTaskStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Otvoren"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dodijeljen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "U tijeku"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Završeno"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Otkazano"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VolunteerTaskTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Šetnja"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hranjenje"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Čišćenje"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Socijalizacija"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Prijevoz"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Administracija"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Animal", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.AnimalStatus", "AnimalStatus")
                        .WithMany("Animals")
                        .HasForeignKey("AnimalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnimalStatus");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Donor", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.DonorStatus", "DonorStatus")
                        .WithMany("Donors")
                        .HasForeignKey("DonorStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzilEdu.Shared.Models.DonorType", "DonorType")
                        .WithMany("Donors")
                        .HasForeignKey("DonorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonorStatus");

                    b.Navigation("DonorType");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Employee", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.EmployeePosition", "EmployeePosition")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzilEdu.Shared.Models.EmployeeStatus", "EmployeeStatus")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeePosition");

                    b.Navigation("EmployeeStatus");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Volunteer", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.VolunteerStatus", "VolunteerStatus")
                        .WithMany("Volunteers")
                        .HasForeignKey("VolunteerStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VolunteerStatus");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTask", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AzilEdu.Shared.Models.Volunteer", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AzilEdu.Shared.Models.VolunteerTaskStatus", "VolunteerTaskStatus")
                        .WithMany("Tasks")
                        .HasForeignKey("VolunteerTaskStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzilEdu.Shared.Models.VolunteerTaskType", "VolunteerTaskType")
                        .WithMany("Tasks")
                        .HasForeignKey("VolunteerTaskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Volunteer");

                    b.Navigation("VolunteerTaskStatus");

                    b.Navigation("VolunteerTaskType");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AnimalStatus", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonorStatus", b =>
                {
                    b.Navigation("Donors");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonorType", b =>
                {
                    b.Navigation("Donors");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.EmployeePosition", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.EmployeeStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerStatus", b =>
                {
                    b.Navigation("Volunteers");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTaskStatus", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTaskType", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
